name: "Deploy app to Fly.io"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy app to Fly.io"
    runs-on: ubuntu-latest
    concurrency: deploy-group

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup Flyctl"
        uses: superfly/flyctl-actions/setup-flyctl@1.5

      - name: "Deploy to Fly.io"
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
