name: "Deploy app to Fly.io"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy app to Fly.io"
    runs-on: ubuntu-24.04-arm
    concurrency: deploy-group

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup Flyctl"
        uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # 1.5

      - name: "Deploy to Fly.io"
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
